### PR TITLE
Copyright 2016 -> 2017

### PR DESCRIPTION
**Pull request by shoujii**
Changed the Copyright in many comments and in the visible about page to 2017...

### CODE REVIEW

**Comment by alecpl** [comment]
Copyright date/year is not a simple subject, but we have a custom of updating the year only with significant changes in the file. So, I'd not apply these. Only change in about.html make sense. @thomascube what do you think?

**Comment by BoBBer446** [comment]
Maybe it makes sense to Update the Year because we are in 2017 and this Software has a copyright in 2017. Why dont show it?

**Comment by marclaporte** [comment]
Please don't do commits for this. It pollutes the logs.
https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by alecpl** [comment]
We removed year from copyright headers.

**Pull request closed without merging**
