### PR TITLE
Elastic: icons cleanup

### PR DESCRIPTION
**Pull request by thomascube**
- Distinct icons for settings and options
- Distinct icons for expand actions (threads)
- Consistent icon to enable select checkboxes

(this is an extract from #6796 for individual consideration)

### CODE REVIEW

**Comment by alecpl** [comment]
1. This breaks "Export selected" icon in Contacts toolbar menu because it uses `.selection` class that changed font-weight in your PR.
2. I'm not sure I like changes in Threads menu, but it is not a strong objection. Also, the "Expand unread" should probably use the same icon as "Unread" option in selection menu.
3. What do you think about changing the "Invert" icon in selection menu to https://fontawesome.com/icons/check-square?style=solid ? I.e. it would be invertion of the Selection icon. Other ideas?

**Comment by thomascube** [comment]
>     1. This breaks "Export selected" icon in Contacts toolbar menu because it uses `.selection` class that changed font-weight in your PR.

I'll check on that.

>     2. I'm not sure I like changes in Threads menu, but it is not a strong objection. Also, the "Expand unread" should probably use the same icon as "Unread" option in selection menu.

I think it's still better than having the same icon for three different actions.

>     3. What do you think about changing the "Invert" icon in selection menu to https://fontawesome.com/icons/check-square?style=solid ? I.e. it would be invertion of the Selection icon. Other ideas?

I don't think this icon would be an improvement but unfortunately I don't have a better suggestion.

**Comment by thomascube** [comment]
@alecpl Do you think this PR is eligible to be merged with the fix for the export selected menu icon?

**Comment by alecpl** [comment]
Sorry for the delay, I was on my vacation. We can ignore point 3, and 1. is done, but for 2. I'm not sure. the "Expand unread" icon is inconsistent. Also, if you see Reply all or Forward or Download menu, you'll see that it's not that unusual to have the same icon for all options. Personally I prefer this over use of some possibly not clear icons.

**Comment by thomascube** [comment]
@alecpl Icon for "expand unread" fixed. Using the same icon for different actions more seems like a bug to me. If we can't find distinct icons, we better do not show any at all.

**Pull request merged**
