### PR TITLE
Fix spelling of occurred

### PR DESCRIPTION
**Pull request by pepsiman**

### CODE REVIEW

**Comment by alecpl** [comment]
I fixed this via Transifex service (https://www.transifex.com/roundcube/roundcube-webmail) now. Please use the service for further translation fixes.

**Comment by pepsiman** [comment]
This isn't a translation fix - the error is in the original language.

**Comment by alecpl** [comment]
The original language is en_US.

**Comment by pepsiman** [comment]
Yes, occurred has 2 rs in en_US.

**Comment by alecpl** [comment]
Then provide a PR for en_US. All the rest is via Transifex. Thanks.

**Pull request closed without merging**
