### PR TITLE
Added GSSAPI support for issue #5779

### PR DESCRIPTION
**Pull request by neilmunday**
Ref: issue #5779 

Notes:

- requires updated Net_Sieve class see https://github.com/roundcube/Net_Sieve/pull/2 for updated class.
- requires krb_authentication plugin
- set $config['managesieve_auth_type'] = 'GSSAPI'; in config.inc.php to use

### CODE REVIEW

**Comment by alecpl** [comment]
I think it requires some changes to krb_authentication plugin so it configures managesieve_connect hook parameters. Right? It would also force auth_type automatically.

Could you also update the code to set CN param added in https://github.com/pear/Net_Sieve/commit/16aa77535038eb09276e8b3dc8311752f41b2a49 ?

**Comment by neilmunday** [comment]
I'll see what I can do.

**Comment by neilmunday** [comment]
I've added the requested changes and update managesieve to use the latest version of the Sieve class from Net_Sieve.

Please also this pull request https://github.com/pear/Net_Sieve/pull/7 which fixes a typo in the Sieve.php class. Without this typo fixed, the managesieve plugin will not work.

**Comment by alecpl** [comment]
Please, in future don't use tabs in the code.

**Pull request merged**
