### PR TITLE
Allow to add Roundcube as app to supported browsers using manifest.json

### PR DESCRIPTION
**Pull request by rstefko**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@rstefko: Maybe you can update the title, it is not only iOS ^^

**Comment by pabzm** [comment]
This has been superseeded by #9354, I guess. I'd close it in favour of the other one because that contains many more cases – or is there a good argument for keeping this open?

(This has the same problem as the #9354, which is making it much harder for e.g. providers to change the logo.)

**Comment by Neustradamus** [comment]
.

**Comment by pabzm** [comment]
I'm closing this due to a lack of activity as suggested in May.

**Pull request closed without merging**
