### PR TITLE
prevent referrer leaking

### PR DESCRIPTION
**Pull request by ghost**
For enhanced privacy, referrer leaking should be avoided.

### CODE REVIEW

**Comment by alecpl** [comment]
Any examples of a referrer leak in Roundcube?

**Comment by evildead45** [comment]
I read about a website privacy check tool at https://webbkoll.dataskydd.net/en in a blog (https://www.kuketz-blog.de/webbkoll-wie-datenschutzfreundlich-ist-deine-webseite/#more-49964) and tried it on my instance of roundcube. It reported "referrers leaked" to me.

This topic is more like a general privacy aspect. Please find more thoughts about this at https://go-to-hellman.blogspot.de/2015/06/protect-reader-privacy-with-referrer.html

I would like to have the websites I host on my server as privacy friendly as possible. Avoiding referrer leaking is another step into this direction.

**Comment by CRtEurope** [comment]
The referer is not sent for HTTPS connections, per RFC 2616, so there's yet another good reason for just using HTTPS

**Comment by evildead45** [comment]
My setup is HTTPS only and it still reported "referrers leaked".

I think you refer to the following passage of the RFC:

> 15.1.3 Encoding Sensitive Information in URI's
   [...]
   Clients SHOULD NOT include a Referer header field in a (non-secure)
   HTTP request if the referring page was transferred with a secure
   protocol.
   [...]

This would mean it is allowed to send the referrer to a HTTPS request.

**Comment by alecpl** [comment]
My point was that we already have some referrer protection code. So, I'd like to see a use-case or maybe web browser version when it does not work. I see we have #4976 still open, but I'm not sure the solution proposed here is right.

**Comment by evildead45** [comment]
As mentioned, the test suite at https://webbkoll.dataskydd.net/en complained about referrer leaking and suggests adding `<meta name="referrer" content="no-referrer">` to the `<head>` section of the page. They also link to http://caniuse.com/#feat=referrer-policy, which lists the browsers that support this setting.

**Comment by CRtEurope** [comment]
Very strange according to RFC 2616...
Nevertheless, due to security whe should not wait until something happens... and should implement it

**Comment by CRtEurope** [comment]
I have just tested your code @evildead45 - It is working great. Thank you very much this.

**Comment by evildead45** [comment]
Thanks a lot! I just added a check to only allow valid values for the referrer.

**Comment by alecpl** [comment]
I'm curious if that test suite tests real leaks or just checks for the meta tag existence ;)

Anyway, I'm not in opposition to this idea, but maybe we could improve it:
1. Some users may actually want referrer to work on the login screen. So, maybe better to use this only for authenticated pages.
2. We already use noreferrer for links and no one complained, so maybe making this new feature configurable is useless. I propose to always use "no-referrer" value for best privacy.
3. Some browsers (Edge, Safari) does not support "no-referrer" (and other values), but support "never", it would be good to set the value according to detected browser.
4. Finally, .htaccess file already contains an example how to do the same with Content-Security-Policy header.

**Comment by evildead45** [comment]
@alecpl 
1: Can you give me an example please, when you might like a referrer on the login page? What could be the benefit? I personally would like to have the "no-referrer" everywhere, so maybe we could introduce two settings if need be: one for authorised and another for unauthorised pages. Maybe with the setting for unauthorised defaulting to the setting for authorised?
2: Maybe we could have it configurable with default to no-referrer? So people that do want to change the behaviour could do so and those who don't benefit from best privacy.
3: I think, browsers should stick to the referrer-policies listed at https://www.w3.org/TR/referrer-policy/#referrer-policies. For Edge there is a ticket stating the same: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7119603/
4: Yes, CSP could be used as well. Also the "Referrer-Policy" header could be an option.

**Comment by alecpl** [comment]
@evildead45 if you use default login page keeping referrer on logon page would not change anything for you (as there will be no external connections), but if someone modified login page adding some (commercial) content there he might be interested in how it works from marketing perspective. Of course I can imagine an opposite need. So, a three-state option would be enough (all, auth, none).

Referrer-Policy is a new thing and not many browsers support it. CSP is more common.

**Comment by evildead45** [comment]
@alecpl I agree to both. When I find time I will look into it.

**Comment by thomascube** [comment]
Looks like an extended version of #5674 but using a `meta` tag instead of a HTTP header. Both seems to be suggested by https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery-meta.

I'd vote for using headers in favor of a `meta` tag.

**Comment by alecpl** [comment]
Implemented in 186f21c4c.

**Pull request closed without merging**
