### PR TITLE
Add managesieve hook to modify extensions

### PR DESCRIPTION
**Pull request by tomsommer**
Add plugin hook to managesieve to manipulate extensions returned by server

### CODE REVIEW

**Comment by tomsommer** [comment]
Also helps out #4615

**Comment by alecpl** [comment]
What is the use-case? The mentionet ticket is very old, and there is a config option to disable specific extensions. You can also set 'disabled' item on `managesieve_connect` hook.

**Comment by tomsommer** [comment]
The use-case is to remove the 'redirect' extension from the UI.

**Comment by alecpl** [comment]
So, it is already possible.

**Comment by tomsommer** [comment]
It's not, managesieve_disabled_extensions does not affect the 'redirect' extension:

        $select_action->add($this->plugin->gettext('messageredirect'), 'redirect');

**Comment by alecpl** [comment]
Redirect is not an extension. Your way will not work either.

**Comment by tomsommer** [comment]
Hrm, correct. I will think of another way

**Pull request closed without merging**
