### PR TITLE
TinyMCE 5

### PR DESCRIPTION
**Pull request by alecpl**
Because of many TinyMCE 5 bugs I think we should not merge it into Roundcube 1.4 yet.

Here's a list of most prominent issues:
- https://github.com/tinymce/tinymce/issues/4865
- https://github.com/tinymce/tinymce/issues/4863
- https://github.com/tinymce/tinymce/issues/4862
- https://github.com/tinymce/tinymce/issues/5003

Maybe none of them is serious, but all together give impression of unfinished product. There are [more tickets](https://github.com/tinymce/tinymce/issues/created_by/alecpl) I created there.

https://kolabian.wordpress.com/2019/05/23/tinymce-5/

### CODE REVIEW

**Comment by trasherdk** [comment]
289 commits. Damn....

**Comment by alecpl** [comment]
Yeah, I messed it with some rebase. I'm not exactly sure what happened. I'll clear that out.

**Comment by trasherdk** [comment]
Maybe a `squash` ? :)

**Comment by alecpl** [comment]
Close in favor of  #7403.

**Pull request closed without merging**
