### PR TITLE
Update to TinyMCE 5.1

### PR DESCRIPTION
**Pull request by EwoutH**
- Update TinyMCE from 4.8.2 to 5.1.5 in jsdeps.json
 - Update SHA-1 hash

As far as I can see none of the [breaking changes](https://www.tiny.cloud/docs/migration-from-4x/) in TinyMCE 5 affect RoundCube, but please help testing, especially the media file selector since it uses some custom CSS.

### CODE REVIEW

**Comment by alecpl** [comment]
There are breaking changes. See #6762.

**Comment by EwoutH** [comment]
@alecpl Thank you for the quick reply! All 4 issues listed in PR 6762 are now closed. In my repo it also passed the CI, something it didn't do in the earlier PR.

**Comment by EwoutH** [comment]
I now see there are a lot more open issues with TinyMCE 5, a lot of which you reported. Thanks for all your work on RoundCube so far!

**Comment by alecpl** [comment]
Some issues are irrelevant as I decided we'll not use mobile theme (which is deprecated). Still there's some things to consider and work on, but I'm on it. I also am waiting for TinyMCE 5.2. We have time to do the switch in 1.5, it will not be backported to 1.4 anyway.

**Pull request closed without merging**
