### PR TITLE
Fix test by make sorting independent of locale and case

### PR DESCRIPTION
**Pull request by pabzm**
These tests have been failing locally repeatedly. This fixes them and also works in the CI.

### CODE REVIEW

**Comment by pabzm** [comment]
@alecpl Do you have a comment on this? I'm not really sure why you chose a case-sensitive comparing function in the first place.

**Comment by alecpl** [comment]
We use `strcoll` because it is locale-aware.

**Comment by pabzm** [comment]
But then we cannot compare its output with a fixed list, right? Because the output depends on the locale?

**Comment by alecpl** [comment]
The solution is to set locale in the test.

**Comment by pabzm** [comment]
I tried without success.

```
putenv('LANG=C');
putenv('LC_ALL=C');
$_ENV['LANG'] = 'C';
$_ENV['LC_ALL'] = 'C';
setlocale(\LC_ALL, 'C');
```

These all don't help, neither with `C.UTF-8` nor `en_US.UTF-8`. Which one is correct needle for this haystack?

I still don't understand what we gain from depending our test result on one specific locale, which we then have to pin in our test?

**Comment by alecpl** [comment]
The test works with `setlocale(\LC_ALL, 'en_US.UTF-8')`, but you have to have this locale installed in the system. It fails with 'C' locale.

Feel free to modify the test to pass (e.g. use upper-case where needed), but I don't think we should change the sorting algorithm.

**Comment by pabzm** [comment]
Does this work for you?

**Pull request merged**
