### PR TITLE
Add override method attributes

### PR DESCRIPTION
**Pull request by mvorisek**
Helpful to detect removed/renamed parent methods of parent, possibly external, classes.

Generated based on phpstan data.

https://stitcher.io/blog/override-in-php-83 describes the advantages, for more details see https://wiki.php.net/rfc/marking_overriden_methods RFC

### CODE REVIEW

**Comment by alecpl** [comment]
I'd like you to rather focus on fixes first, please. This is more like a feature.

**Comment by alecpl** [comment]
BTW, I'm not a fan of this one.

**Comment by mvorisek** [comment]
Most of the CS changes has been landed, now let's land this PR too.

**Comment by mvorisek** [comment]
@alecpl let's merge this PR.

https://stitcher.io/blog/override-in-php-83 describes the advantages, for more details see https://wiki.php.net/rfc/marking_overriden_methods RFC. No BC break.

**Comment by mvorisek** [comment]
@alecpl, in https://github.com/roundcube/roundcubemail/pull/9272#issuecomment-1859197006 you have written you are not fan of this change, I have updated the PR description to explain the advantages better. Did it addressed your concerns or do you still have some questions?

**Comment by mvorisek** [comment]
@alecpl can I ask you to merge this PR as well?

**Pull request merged**
