### PR TITLE
Privacy: Remove roundcube version string in header

### PR DESCRIPTION
**Pull request by Rotzbua**
Avoid unnecessary information leakage.

Less metadata for NSA & Friends.

### CODE REVIEW

**Comment by alecpl** [comment]
I have no strong opinion, but maybe we should not set the header at all by default?

**Comment by Rotzbua** [comment]
I think for backwards compatibility it would be better to keep a identifying header. The scenario could be that roundcube produces false-positives at the spam filter and so a extra rule depending on the header can avoid the false-positives. I do not work with mail servers and spam filters so I do not know how realistic this scenario is...

**Comment by Rotzbua** [comment]
@alecpl Rebased the pr and solved the conflict. Have you made a decision?

**Comment by Rotzbua** [comment]
Obsolete by 6b8881271f271422c259a33d842fcd1979baa4c8

**Pull request closed without merging**
