### PR TITLE
add identity management script

### PR DESCRIPTION
**Pull request by vladasko-g**
A shell script used to manage identities.

use case - automation that aims to synchronize roundcube settings with mailserver settings

### CODE REVIEW

**Comment by vladasko-g** [comment]
not 100% sure how identities_level should be managed so I try to be strict, any comments would be useful

**Comment by vladasko-g** [comment]
I didn't update all other places where get_host might possibly be used as I'm not really comfortable with all other places of the app

**Comment by vladasko-g** [comment]
I updated the code according to @alecpl comments in the former PR https://github.com/roundcube/roundcubemail/pull/8839 it would be great to have more feedback

**Comment by matejak** [comment]
Hello @alecpl and perhaps @thomascube, could you please check this PR out? I also thing that it is useful, especially when it comes to the need of advanced automated administration.
Are you aware of any bits or perhaps documentation/rationale that is missing?

**Pull request merged**
