### PR TITLE
oauth: select auth scheme (XOAUTH2 vs OAUTHBEARER)

### PR DESCRIPTION
**Pull request by EdouardVanbelle**
This is a WIP, will need new version of Net_SIEVE & Net_SMTP

### CODE REVIEW

**Comment by EdouardVanbelle** [comment]
Dependencies:
- https://github.com/pear/Net_Sieve/pull/11
- https://github.com/pear/Net_SMTP/pull/79

and their respective new releases

(cc @alecpl)

**Comment by Neustradamus** [comment]
@EdouardVanbelle: Can you send me an email?
I have not found yours.
My username @ hotmail dot com
Thanks in advance.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9274
- https://github.com/roundcube/roundcubemail/pull/9289
- https://github.com/pear/Net_SMTP/pull/79
- https://github.com/pear/Net_Sieve/pull/10
- https://github.com/pear/Net_Sieve/pull/11

**Comment by alecpl** [comment]
New versions of Net_Sieve and Net_SMTP has been released. @EdouardVanbelle do you mind finishing this PR, please.

**Comment by Neustradamus** [comment]
@alecpl: Thanks!

Next part is about SCRAM-SHA-* ^^

**Comment by EdouardVanbelle** [comment]
Many thank's @alecpl !

Yes @Neustradamus , I have a very low bandwidth :(

**Pull request merged**
