### PR TITLE
get rid of jquery diff files

### PR DESCRIPTION
**Pull request by progsmile**
In order to cleanup repo, unused diffs were removed.

### CODE REVIEW

**Comment by alecpl** [comment]
Why would you do that?

**Comment by progsmile** [comment]
Updated.

**Comment by alecpl** [comment]
We're using them after we update jquery-ui, because they contain our changes to the vanilla code.

**Comment by progsmile** [comment]
Ok, supposed they are unused. Another solution might be creating one more css file with overriden rules for jquery original styles.

**Pull request closed without merging**
