### PR TITLE
Fix plugins composer.json format

### PR DESCRIPTION
**Pull request by mvorisek**
needed for #9241

also simplify phpunit configs

### CODE REVIEW

**Comment by mvorisek** [comment]
@alecpl might I ask you to merge this PR so I can continue with #9241?

**Comment by alecpl** [comment]
Independently from this PR I'm wondering why number of unit tests is different on e.g. PHP 7.3 and PHP 8.3.

**Comment by mvorisek** [comment]
@alecpl run phpunit with `--list-tests`

**Review by tomasreyes — COMMENTED** [review]
Exfellent

**Comment by tomasreyes** [comment]
> needed for #9241
> 
> also simplify phpunit configs

**Pull request merged**
