### PR TITLE
Fix incorrect translate in language file ru_RU

### PR DESCRIPTION
**Pull request by militska**

### CODE REVIEW

**Comment by alecpl** [comment]
This have to be done via https://www.transifex.com/roundcube/roundcube-webmail/

**Comment by militska** [comment]
image

**Comment by m-ueberall** [comment]
> […] the list does not include Russian […]

Sure it does:
tf_ru

**Comment by militska** [comment]
i dont have access , probably

**Comment by alecpl** [comment]
Here more direct link https://www.transifex.com/roundcube/roundcube-webmail/language/ru_RU/

But you have to have a translator account there and request to join the Russian localization team first.

**Comment by militska** [comment]
Russian localization team is not available for me. Maybe I should wait

**Pull request closed without merging**
