### PR TITLE
Fix group creation to work with Net_LDAP3.

### PR DESCRIPTION
**Pull request by eehakkin**
Net_LDAP3::add_entry does not pass empty attributes to ldap_add, thus
let's replace an empty attribute with a non-empty array containing
an empty string as that is supported by ldap_add, too.

### CODE REVIEW

**Comment by alecpl** [comment]
Hmm... Why it is a problem?

**Comment by eehakkin** [comment]
It is a problem because it breaks group creation.

A typically configuration for LDAP contact groups, I suppose, is to use
 * array('groupOfNames') as object_classes,
 * 'cn' as name_attr and
 * 'member' as member_attr

thus $new_entry will be

    array('objectClass' => array('groupOfNames'), 'cn' => $group_name, 'member' => '')

without this patch.

Then Net_LDAP3::add_entry changes that to

    array('objectClass' => array('groupOfNames'), 'cn' => $group_name)

Then ldap_add sends an add operation to an LDAP server, which refuses to complete the operation as the groupOfNames entry is missing a mandatory member attribute.

With this patch, the the groupOfNames entry will have an empty member attribute (instead of none at all). So this patch restores the behaviour which RoundCube had when it used Net_LDAP2.

**Comment by alecpl** [comment]
Indeed, per https://tools.ietf.org/html/rfc4519#section-3.5 the member attribute is required. I didn't notice that because the ldap server I'm using has this class redefined in a way that member attribute is not required.

Anyway, your fix is not good. On my server setting 'uniquemember' attribute to an empty array or array with an empty element on group creation gives "Invalid syntax" or "Protocol error". So, maybe we need some config option.

**Comment by dereks** [comment]
Thank you for submitting a Pull Request (PR) to the Roundcube GitHub project.

You are receiving this message because your PR has conflicts which need to be resolved. We are trying to catch up on our backlog of old PRs and get them merged in (where appropriate). Therefor, we request the following:

**Step 1.** Rebase from the latest Roundcube branch master into your PR.

```
git fetch upstream
git checkout your_feature_branch_name
git rebase upstream/master
git push -f origin your_feature_branch_name
```

**Step 2.** Re-test to make sure your new code still works as expected

**Step 3.** Comment back here once it has been tested and will merge cleanly.

Once this has been done we will treat it like a new Pull Request and consider it for acceptance.

Apologies for the inconvenience. Thank you for contributing to Roundcube!

**Pull request closed without merging**
