### PR TITLE
fix wrong "text" parsing

### PR DESCRIPTION
**Pull request by skiner68**
accept lines containing dots only - I thing check position index should be $position, not $pos

### CODE REVIEW

**Comment by alecpl** [comment]
Looks like you might be right, but do you have a sample sieve script that fails to parse correctly? I'd like to add a test for this.

**Comment by alecpl** [comment]
Nevermind, I fixed this in  8b61d6a2d1.

**Comment by skiner68** [comment]
Great, you were fast. Just one thing - should not $position be incremented once more in case line ends with "\r\n"? Honestly I have not checked this practically, but length of "\r\n" is 2 symbols, not 1 symbol like in case of simple "\n", so the $position value may be wrong in this case. Please see my original pull request.

**Comment by alecpl** [comment]
You're right. I couldn't find a sample that breaks without this, but I fixed it anyway.

**Pull request closed without merging**
