### PR TITLE
return 204 rather than 404 on missing contact photo

### PR DESCRIPTION
**Pull request by johndoh**
for #7777

### CODE REVIEW

**Comment by johndoh** [comment]
I've added a small change in `rcmail_action_mail_show::message_contactphoto()` to remove the hard coded image path.

**Comment by alecpl** [comment]
Quite a lot of plugins use the blank.gif image. I suggest to keep it, even if it's not used by the core.

**Comment by johndoh** [comment]
Done. I thought it might be confusing to have it there when the core uses the constant set in rcmail_output rather than this file.

**Comment by ADDISON74** [comment]
It seems that you must be contributor to this project in order for a reported issue to be considered. The same issue was reported by me here #7765 and it was closed with "not a bug" phrase.

Perhaps a peaceful approach on the part of some may be needed in the future.

**Pull request merged**
