### PR TITLE
Add support for :from in managesieve/vacation plugin

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by alecpl** [comment]
Nice, thank you. Maybe you would like to work also on http://trac.roundcube.net/ticket/1489221 ?

**Comment by mlocati** [comment]
I have dovecot 2.2.9 (standard for Ubuntu 14.04.3 LTS) and if the `:from` field is not set, the sender address of the vacation is correct (I don't have that `system_user@server_hostname` problem) for me.

I mean, if the vacation rule gets fired because someone writes to the address X (and X is in the `:addresses` field), the automatic reply is sent using X as the sender.

So, IMHO http://trac.roundcube.net/ticket/1489221 refers to an older dovecot version, and it could be closed...

**Comment by alecpl** [comment]
An option to fill the field automatically or autocompletion/selection for user emails might be a good addition still, but if you don't want to spend time on this it is fair enough.

**Comment by mlocati** [comment]
Sorry, but I won't have any spare time for some time...

**Comment by alecpl** [comment]
Committed with small improvements in 162bc85be9ded

**Pull request closed without merging**
