### PR TITLE
add delete field to message list

### PR DESCRIPTION
**Pull request by johndoh**
Inspired by #7141

Untitled-1

Currently when hovering over a message in the list, for messages which are not flagged, a flag icon is displayed in the top right corner of the row. Also the message date is replaced with the message size.

This PR adds a new delete column to the message list so that in widescreen view a delete icon can be shown in additional to the flag icon. This delete icon is shown directly below the flag icon. For messages which have attachments the attachment icon is replaced by the delete icon on hover.

*This is a breaking change*.
A new span for the delete icon is added into the `flags` \<td\>.  I can create PRs for the legacy Classic and Larry skins to prevent display issues.

### CODE REVIEW

**Comment by alecpl** [comment]
The hover effect on the icon is wrong: i.e. the color should not be red and the icon should not change. Also make sure to use the same icon as in the toolbar.

I wonder whether, after we merge this, it would make sense to use this new icon/position for the Undelete action (now we're using the icon on the left of the subject line). I guess it would have pros and cons.

**Comment by johndoh** [comment]
I have changed the delete icon to match the one in the toolbar exactly and removed the hover effects I added.

I have also added the restore icon for undelete action

**Comment by alecpl** [comment]
@johndoh I did not forgot about this. The solution I had in mind was something like this:

hover-menu

It will take time for me to implement this though. I think it will have some adventages.

Plugins could add icons there easier (of course too many might be problematic, in future we may make this configurable). I removed the icon/button from the subject line, maybe we could also remove the flag icon/button at all and keep only the red color as a flag indication.

For keyboard-only users we'd need a way to display the menu, maybe using Right-Arrow and Left-Arrow keys.

Potentially we could put folder name in this menu, but it might not look that good. Something to investigate.

Then it might be a good idea for your swipe plugin's default behavior. Swipe left displays this menu. Swipe right hides it.

**Comment by johndoh** [comment]
I like the idea of a "message actions" field where the actions in the field could be customised.

I think the flag icon should stay, people are used to seeing that in mail clients and it might not be so obvious what only highlighting a message in red means, also for accessibility with colour blind people.

While the Elastic skin does not support the desktop/list view I think this also needs to be considered as we know some users like that display, we should not deprecate the functionality.

**Pull request closed without merging**
