### PR TITLE
Add PHPUnit 10.x and 11.x support

### PR DESCRIPTION
**Pull request by mvorisek**
follow up for #9477

### CODE REVIEW

**Comment by alecpl** [comment]
Can we do something with these phpunit deprecation warnings when using phpunit >= 10?

**Comment by mvorisek** [comment]
The phpunit deprecation warnings are gone, good catch!

**Comment by mvorisek** [comment]
@alecpl this PR is done

I wonder also why such phpunit upgrade was not tried by Dependabot.

**Comment by alecpl** [comment]
Maybe because of our minimum PHP version? I have no idea.

**Comment by mvorisek** [comment]
@alecpl can it be merged?

**Pull request merged**
