### PR TITLE
Add OAuth/XOauth support

### PR DESCRIPTION
**Pull request by thomascube**
Implement support for OAuth2 user logins and IMAP/SMTP authentication.
See issue #6933 for background and details.

The PR contains example config parameters for Gmail and Outlook (Office 365) logins although the latter could not be confirmed to work with free Outlook.com accounts. Further improvements can happen in upstream master as the feature is completely optional.

### CODE REVIEW

**Comment by alecpl** [comment]
Looks good, but I would prefer this to be implemented as a plugin.

**Comment by thomascube** [comment]
If you look at the code, it requires some additions that directly affect core components. So what's the difference between enabling OAuth with a config option or by a plugin? FWIW, we also have funny features like exporting contacts as QR code in core so why not adding OAuth support right there?

**Comment by alecpl** [comment]
This feature is considerably bigger that qr code, and authentication is a more sensitive subject. That's why I'd prefer it separated, but I will not insist.

**Comment by thomascube** [comment]
I still think this feature qualifies to be implemented in core. If sensitivity is a concern (I assume you mean the code should not be loaded unless enabled) we could still add some more `$rcmail->oauth->is_enabled()` checks in `oauth.inc` and other places.

**Comment by TuxCoder** [comment]
@thomascube Thanks, nice work.
Could successfully test your patch in combination with dovecot ( imap/submission ).
Had to tweak some other software, but had no problems with this code.

some suggestions after testing:

Consider to use a oauth libary, there are many security mistakes that can happen, I don't see currently one, but be carefully by implementing it by yourself.

jwks url is not definable
autoconfig with well know url is not implemented: https://accounts.google.com/.well-known/openid-configuration


I have some problems with refresh_token, not sure if its the fail from dovecot, also get some strange logs there.
if I find any issues with this PR I will report.

**Comment by quenenni** [comment]
@thomascube Hey. Thanks for this.

I tried it with our Keycloak, but, when keycloak redirect back to roundcube, I have the login form page (but without css) and I'm not connected.

Here is the address keycloak is using:
```
htpp://my.roundcube/index.php/login/oauth?state=xxxxxx&session_state=yyyyyyy&code=zzzzzzzzz
```

From my debug, I noticed the RCMAIL->action is empty and RCMAIL->task = login.
Because of that, in index.php, the test
```
// handle oauth login requests
else if ($RCMAIL->task == 'login' && $RCMAIL->action == 'oauth' && $RCMAIL->oauth->is_enabled()) {
```
is not working and thus the file 'program/steps/login/oauth.inc' is not included and executed and the function request_access_token is never called.

Problem with my keycloak config or in your code, I can't say. I'm stuck at this point.
Any idea on this?

I was not sure this was the right place to say this but couldn't find a better one.
If it's not, please point me to the right place and I'll move this ticket.

And really, big thanks.

**Comment by TuxCoder** [comment]
Yes I can also confirm the error, when something goes wrong while the Oauth2 process (invalid client credentials, flow error, ...) it redirects you to a login page without css an the error only mention in the url.
for example:
`https://webmail.xxx.xx/index.php/login/oauth?code=xxx.xxx&scope=openid%20email%20email_access&state=MZSKoTz7dP3I`
To be said, there is an error in the log, but none on the interface.
Would be also nice to improve this for easier see the error messages and don't look like something is wrong with roundcube itself.

@quenenni 
I also get a similar redirect with the same parameters after login,
but then i got redirected to the inbox with a successfully login.

What helps me to debug:
 * enable permanent log in your browser
 * see all log files, oauth provider, mail server, roundcube log (enable in config)
   * does it try to login to dovecot?
   * does it fetch the access token from keyclock ( `.../token` )
   * does keyclock say any error (invalid client, ...) ?
 * do you get any message in the redirect urls?

My testsetup was hydra(upstream version), dovecot (upstream version), roundcube (this PR).

**Comment by quenenni** [comment]
@TuxCoder Thanks a lot for all your good advices.
I put here all the debug / config infos I could find.

* Rouncdube Auth config:
```
$config['oauth_provider'] = 'keycloak';
$config['oauth_provider_name'] = 'SSO';
$config['oauth_client_id'] = "roundcube";
$config['oauth_client_secret'] = "<the secret I got from keycloak for this client>";
$config['oauth_auth_uri'] = "https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/auth?";
$config['oauth_token_uri'] = "https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/token";
$config['oauth_identity_uri'] = null;
$config['oauth_verify_peer'] = true;
$config['oauth_scope'] = "email profile roles openid";
$config['oauth_auth_parameters'] = ['access_type' => 'offline'];
$config['oauth_identity_fields'] = null;
$config['oauth_login_redirect'] = false;
```

* Roundcube log config:
All the debug options in roundcube are set to true except one:
```
$config['per_user_logging'] = false;
$config['smtp_log'] = true;
$config['log_logins'] = true;
$config['session_debug'] = true;
$config['sql_debug'] = true;
$config['imap_debug'] = true;
$config['ldap_debug'] = true;
$config['smtp_debug'] = true;
$config['memcache_debug'] = true;
$config['apc_debug'] = true;
$config['redis_debug'] = true;
```

* Keycloak roundcube client config (it's more than possible that the problem comes from her as I'm quite new to SSO and very new to openID connect):
```
SETTINGS :

  Client ID : rouncube
  Name : Roundcube
  Enabled: ON
  Consent Required : OFF
  Client Protocol : openid connect
  Access Type : confidential
  Standard Flow Enabled : ON
  Implicit Flow Enabled : OFF
  Direct Access Grants Enabled : ON
  Service Accounts Enabled : ON
  Authorization Enabled : ON
  Root URL : https://my.roundcube.host/
  Valid Redirect URI : https://my.roundcube.host/*
  Web Origins : https://my.roundcube.host

CLIENT SCOPE :

  Assigned Default Client Scopes : email / profile / roles / web-origins
  Assigned Optional Client Scopes : address / microprofile-jwt / offline_access / phone

MAPPERS :

  Client Host 
    Mapper Type: User Session Note
    User Session Note : clientHost
    Token Claim Name: clientHost
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON

  Client IP Address
    Mapper Type: User Session Note
    User Session Note : clientAddress
    Token Claim Name: clientAddress
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON

  Client ID
    Mapper Type: User Session Note
    User Session Note : clientId
    Token Claim Name: clientId
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON

  Mail
    Mapper Type: User Property
    Property : email
    Token Claim Name: email
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON
    Add to userinfo : ON

  Uid
    Mapper Type: User Property
    Property : usenrame
    Token Claim Name: uid
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON
    Add to userinfo : ON

SCOPE

  Full Scope Allowed : ON
```

* Debug info of the flow
  - From Roundcube, I'm redirected to keycloak login form
  - I validate my credentials.
    - In server.log from keycloak, just after the ldap connection to validate my credentials, from what I could gather, the process is successfull ([keycloak-server.log](https://github.com/roundcube/roundcubemail/files/4865070/keycloak-server.log))
    - I'm redirected to my roundcube with a link like this one:
```
htpp://my.roundcube/index.php/login/oauth?state=xxxxxx&session_state=yyyyyyy&code=zzzzzzzzz
```
I can see the params aren't the same as yours. I don't have the scope param and you don't have the session_state param in your example.
  - About my roundcube / dovecot / postfix server, I have nothing in the logs at that point. 
    - There are nothing in log files from dovecot, so no attempt to connect, and also, no queries in the Ldap to show it tried something.
    - Roundcube logs only show few update queries to the session table.
```
[02-Jul-2020 16:18:35 +0200]: <81k81ev6> [1] SELECT `vars`, `ip`, `changed`, now() AS ts FROM `session` WHERE `sess_id` = 'XXXXXXXXX';
[02-Jul-2020 16:18:35 +0200]: <81k81ev6> [2] INSERT INTO `session` (`sess_id`, `vars`, `ip`, `changed`) VALUES ('XXXXXXXXXX', '<lon string here>', '111.222.333.444', now());
```
* From the browser console perspective.
When clicking on the button "Log in with ..", here is what I have (copied the curl equivalent requests):
```
curl 'http://my.roundcube.host/?_task=login&_action=oauth' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: fr-BE,en-US;q=0.7,en;q=0.3' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://my.roundcube.host/' -H 'Cookie: roundcube_sessid=yyyyyyyyyy; PHPSESSID=zzzzzzzzz' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
=> Return code 302

curl 'https://mykeycloak.host/auth/realms/test_saml/protocol/openid-connect/auth?&response_type=code&client_id=roundcube&scope=email+profile+roles+openid&redirect_uri=http%3A%2F%2Fmy.roundcube.host%2Findex.php%2Flogin%2Foauth&state=EQQTqB32HonL&access_type=offline' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: fr-BE,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: http://my.roundcube.host/' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: AUTH_SESSION_ID=XXXXXXXXXXXXX; KEYCLOAK_IDENTITY=YYYYYYYYY; KEYCLOAK_IDENTITY_LEGACY=ZZZZZZZZZ; KEYCLOAK_SESSION=test_saml/AAAAAAAAAAAAA; KEYCLOAK_SESSION_LEGACY=test_saml/AAAAAAAAAAAAAAA' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
=> Return code: 302

curl 'http://my.roundcube.host/index.php/login/oauth?state=XXXXXXX&session_state=YYYYYYY&code=ZZZZZZZZZ' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: fr-BE,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: http://my.roundcube.host/' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: roundcube_sessid=DDDDDDDDDD; PHPSESSID=EEEEEEEEEE' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
=> Return code 200

Then all the other requests to normal roundcube files return a code 404.
```

* Does it fetch the access token from keyclock ( .../token )
Not that I'm aware of
When I go back to my roundcube, I don't have anything more in keycloak logs (except a repetitive 5 lines about a scheduled task)

**Comment by TuxCoder** [comment]
@quenenni 
I think you need to add `oauth_identity_uri`, this should point to your userinfo, this is necessary to show the username/email in roundcube, you can access with the access_token your ressources (mail), but a mailserver will not tell you your username that is needed for login.

**Comment by quenenni** [comment]
I added the config option oauth_identity_uri.
But no change.

I can see that roundcube just don't do anything.

I'm wondering how the $RCMAIL->action could be set to 'oauth' when keyclaok redirect to roundcube after a successfull login.
The link behind the button "Log in with SSO" is `/?_task=login&_action=oauth`. Easy to see from this:
```
$RCMAIL->task = login
$RCMAIL->action = oauth
```
(set in function startup() in program/include/rcmail.php)

But keycloak uses the URI `/index.php/login/oauth` (defined in function login_redirect() in program/include/rcmail_oauth.php).
Why in this case, the $RCMAIL->action is not set to 'oauth'.

Despite that, I managed to set the var $RCMAIL->action to 'oauth' when coming back from Keycloak.
I wanted to see if my param 'code=' was good (in the file /program/steps/login/oauth.inc)
```
$auth_code = rcube_utils::get_input_value('code', rcube_utils::INPUT_GET);
```
But even like this, $auth_code is empty and so the test fails and I'm redirected to Keycloak, that redirects me immediately to roundcube as I'm already logged.. (in an endless spiral).

That's the kind of value I have for the code param:
```
&code=0ded8d0b-aed2-4152-bcc5-bef8fa502054.b282e73c-4942-49e2-b271-636718d3915d.abec1831-6ee2-4e05-bc51-bdf34b98091f
```

Do you know a way to have a decoded view of the data?


And thanks for all the pointers.

With the scopes. I know that my config is very far from good, but I just want a basic working config first.
After that, I'll start over from scratch.

Stil, the tip about "email_access" scope & dovecot is very nice to know.
Thanks.

**Comment by thomascube** [comment]
`/index.php/login/oauth` basically is an alias of `/?_task=login&_action=oauth` and should work with default PHP settings. If it doesn't, try defining a rewrite rule in your webserver config for it.

This is the return URL from OAuth login and that step shall then exchange the authorization code into an access token by posting to the OAuth server (`oauth_token_uri` config option). If the response doesn't contain identity information (field `id_token`), this step also queries the identity endpoint (`oauth_identity_uri` config option) because Roundcube needs an e-mail address of the authenticated user to proceed.

**Comment by quenenni** [comment]
@thomascube Thanks.

Indeed it was not working as intended with a default version of php7.3-fpm / nginx.
I don't know why though it should be like this by default.

And that fixes my problem, at least that one. I so desperately needed it. :+1: 

When I come back to roundcube, I have now the normal login form (with css) and a error msg  "Connection failed".
If I press F5, I have the msg "OAuth login failed. Please try again."

I need to go back to my debugging to see where the problem is now.

Thanks.

----------------------------------------
My nginx vhost was found on the net (https://www.linuxbabe.com/ubuntu/install-roundcube-webmail-ubuntu-18-04-apache-nginx)
```
server {
  listen 80;
  listen [::]:80;
  server_name my.roundcube.host;

  root /var/www/roundcube;
  index index.php index.html index.htm;

  error_log /var/log/nginx/roundcube.error.log;
  access_log /var/log/nginx/roundcube.access.log;

  location / {
    try_files $uri $uri/ /index.php;
  }

  location ~ \.php$ {
   try_files $uri =404;
    fastcgi_pass unix:/run/php/php7.3-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }

  location ~ /.well-known/acme-challenge {
    allow all;
  }
 location ~ ^/(README|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ {
    deny all;
  }
  location ~ ^/(bin|SQL)/ {
    deny all;
  }
 # A long browser cache lifetime can speed up repeat visits to your page
  location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {
       access_log        off;
       log_not_found     off;
       expires           360d;
  }
}
```
and my fix  (before the line `location / {`):
```
    location ~ /index.php/login/oauth {
        rewrite ^/index.php/login/oauth?(.*)$ /index.php?_task=login&_action=oauth&$1 permanent;
    }
```

**Comment by TuxCoder** [comment]
> @thomascube Thanks.
> 
>   location ~ \.php$ {
> ```
> 

this is the nice fix:

` location ~ ^(?!.+\.php/)(?<script_name>.+\.php)$ {`

**Comment by quenenni** [comment]
@TuxCoder Thanks again for your help.

I used your optimized vhost, but I still needed to add my rewrite rule in order to have the /login/oauth/ that is rewrite as _task=login&action=oauth.

My server is a test server with not much on it (I tested Sogo / roundcube & simplesamlphp + I configured dovecot / postfix)
Php was installed and I just changed few options in php.ini when I testd pam_script_saml (to try Sogo / Saml / keycloak), options that I put back to their default values afterwards.
So I pretty sure it's the default params I'm using.

I compared the php.ini from fpm, cli and the one from apache (not touched) and the difference are:
```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT                                           | error_reporting = E_ALL
display_errors = Off                                                                          | display_errors = On
display_startup_errors = Off                                                                  | display_startup_errors = On
;error_log = php_errors.log                                                                   | error_log = php_errors.log
;date.timezone =                                                                              | date.timezone = "Europe/Brussels"
```
Nothing that would explain why I'm not redirected.

Any idea why?

**Comment by TuxCoder** [comment]
@quenenni 
>Any idea why?

not really would need access to the system, probably try from the begin with a proper tutorial how to setup php-fpm with nginx.

php.ini should be not responsible for this issue.
probably check order or copy paste issues.

when its really a rewrite error IMHO the second part of the config should handle with that regex
(as good as I/anybody can read regex)
```
        location ~ ^(?<script_name>.+\.php)(?<path_info>/.*)$ { // << does the spliting
                try_files $script_name =404; 

                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$script_name;
               fastcgi_param PATH_INFO $path_info;  // <<<< important, forwards path info to php enviroment
```

**Comment by quenenni** [comment]
@thomascube 

The other problem I had with the msg "Connection failed", I found that it came from the length of my password.
In the file ./program/include/rcmail.php, function login(), this test failed with a generic msg, so not easy to find the reason behind.:
```
        // check input for security (#1490500)
        if (($username_maxlen && strlen($username) > $username_maxlen)
            || ($username_filter && !preg_match($username_filter, $username))
            || ($password_maxlen && strlen($password) > $password_maxlen)
        ) {
            $this->login_error = self::ERROR_INVALID_REQUEST;
            return false;
        }
```
The password I'm getting from Keycloak is +- 1300 chars and by default, the value is 1024 in config.php:
```
$config['login_password_maxlen'] = 1024;
```

Maybe separate the 3 tests with their own error msg if the test fails.
```
if (($username_maxlen && strlen($username) > $username_maxlen) {
            $this->login_error = ...;
            return false;
} elseif ($username_filter && !preg_match($username_filter, $username)) {
            $this->login_error = ...;
            return false;
} elseif ($password_maxlen && strlen($password) > $password_maxlen) {
            $this->login_error = ...;
            return false;
}
```

But that's amazing progress.
Very nice. Thanks a lot for making this possible.

I know it's a bit out of this branch scope, but maybe my dovecot problem is known from you..
I can see all the process going well up to the connection to Dovecot... and it fails.
```
==> dovecot-debug.log <==   
Jul 03 18:10:11 auth: Debug: oauth2(my.mail@whatever,::1,<t6Wb42p5psAAAAAAAAAAAAAAAAAAAAB>): oauth2: Making token validation lookup to https://my.keycloak.host/auth/realms/test_saml
/protocol/openid-connect/token
Jul 03 18:10:11 auth: Debug: http-client[1]: request [Req1: GET https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/tokeneyJhbGciOiJFUzI1NiIsInR5cCIgOiAiSldUIiwia.....(very long key)]: Error: 9003 Couldn't initialize SSL context: Can't verify remote server certs without trusted CAs (ssl_client_ca_* settings)
Jul 03 18:10:11 auth: Debug: http-client[1]: request [Req1: GET https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/tokeneyJhbGciOiJFUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6IC.....(very long key)]: Submitted (requests left=1)
Jul 03 18:10:11 auth: Debug: oauth2(my.mail@whatever,::1,<t6Wb42p5psAAAAAAAAAAAAAAAAAAAAB>): oauth2: callback(-1, Couldn't initialize SSL context: Can't verify remote server certs without trusted CAs (ssl_client_ca_* settings))
```

On both my dovecot / roundcube and my keyclaok hosts I used lets'encrypt to generat my certifs.
I set this option: `tls_ca_cert_file =/etc/letsencrypt/live/my.host/chain.pem`, but have this error:

```
Jul 03 20:59:41 auth: Debug: http-client[1]: conn 53.191.51.14:443 [0]: SSL handshaking with 53.191.51.14:443 failed: read(SSL 53.191.51.14:443) failed: Received invalid SSL certificate: unable to get issuer certificate: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Jul 03 20:59:41 auth: Debug: http-client[1]: conn 53.191.51.14:443 [0]: (:443): Disconnected: Connection closed: Received invalid SSL certificate: unable to get issuer certificate: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3 (fd=22)
Jul 03 20:59:41 auth: Debug: my.keycloak.host: SSL error: Received invalid SSL certificate: unable to get issuer certificate: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```

I'm not sure to understand what Dovecot is asking? 
What certificate do I have to put in option tls_ca_cert_file? The one from my keycloak server?

Thanks.

--------------
* My Dovecot config:
  - conf.d/10-auth.conf
```
auth_mechanisms = xoauth2 oauthbearer login

# Login via Mail client (TB, ..)
!include auth-ldap.conf.ext
# SSO
!include auth-oauth.conf.ext
```
  - conf.d/auth-oauth.conf.ext
```
# Authentication for OAuth users. Included from 10-auth.conf.
passdb {
  driver = oauth2
  mechanisms = xoauth2 oauthbearer
  args = /etc/dovecot/dovecot-oauth2.conf.ext
}

userdb {
  driver = static
  args = uid=mail gid=mail home=/var/mail/%u
}
```
  - conf.d/10-ssl.conf
```
ssl = yes
verbose_ssl = yes
ssl_cert = </etc/letsencrypt/live/my.host/fullchain.pem
ssl_key = </etc/letsencrypt/live/my.host/privkey.pem
ssl_client_ca_dir = /etc/ssl/certs
# Set to no for now. dovecot won't start if I put yes. hopefully linked to the problem I have.
ssl_verify_client_cert = no 
ssl_dh = </usr/share/dovecot/dh.pem
ssl_cipher_list = ALL:!kRSA:!SRP:!kDHd:!DSS:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4:!ADH:!LOW@STRENGTH
ssl_prefer_server_ciphers = yes
```
  - dovecot-oauth2.conf.ext
```
tokeninfo_url = https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/token
introspection_mode = post
introspection_url = https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/token/introspect
username_attribute = email
tls_ca_cert_file = /etc/letsencrypt/live/my.host/chain.pem
#active_attribute = enableMail
#active_value = TRUE
debug =  yes
rawlog_dir = /tmp/oauth2
```

NB: I had to set to 0777 the folders /etc/letsencrypt/live & /etc/letsencrypt/archive, if not Dovecot couldn't access them.
That's an ez fix for a test env, not a good thing in production. I'll set a script that test if a new certif was emitted and copy them elsewhere for dovecot to have access.

**Comment by quenenni** [comment]
> php.ini should be not responsible for this issue.
> probably check order or copy paste issues.

@TuxCoder 
You're right about php not being responsable. It's about Nginx.
I played with different configurations around pathinfo, but I don't know why, the pathinfo seems not to have the right value or correctly treated.. or something else... everytime I test the /index.php/login/oauth url.

I'm going to leave this like that. I'll be aware of this potential problem when setting the server.

But many thanks for your time and thorough insights.

**Comment by thomascube** [comment]
> The password I'm getting from Keycloak is +- 1300 chars and by default, the value is 1024 in config.php:
> `$config['login_password_maxlen'] = 1024;`

@quenenni Thanks for this finding! We'll just add a not about this either to the example block in config defaults or to the wiki page I'll add for the new OAuth2 feature once this PR is accepted and published with the 1.5 release.

**Comment by thomascube** [comment]
@alecpl What's your final take on this? Do you still require it to be rewritten as a plugin or can it be merged?

**Comment by alecpl** [comment]
You can merge it.

**Comment by downtownallday** [comment]
Hi. I'm not sure this is the correct place to be commenting now that the PR is merged, but here goes, FWIW.

I've been testing this (master branch) against an Authlib-based authorization server using the authorization code flow and a dovecot/postfix backend with roundcube hidden behind an nginx reverse proxy.

The issues I ran into are:

1. redirection

In program/include/rcmail_oauth.php, I had to rewrite the function get_redirect_url() as follows to get anywhere.

I don't know if these problems are my misconfiguration or not.

```
public function get_redirect_uri()
{
        $url = rcube_utils::resolve_url(rtrim($_SERVER["DOCUMENT_URI"], '/') . "/?_task=login&_action=oauth");
        return $url;
}
```

I found that `$this->rcmail->url([], true, true)` in the committed function does not include the nginx stripped portion -- it returns "https://server/?_task=login" when I would have expected "https://server/mail/?_task=login" ($_SERVER["DOCUMENT_URI"] includes the "/mail" prefix). Nginx is configured as follows:
```

	rewrite ^/mail$ /mail/ redirect;
	rewrite ^/mail/$ /mail/index.php;
	location /mail/ {
		index index.php;
		alias /usr/local/lib/roundcubemail/;
	}
	location ~ /mail/config/.* {
		return 403;
	}
	location ~ /mail/.*\.php {
		# note: ~ has precendence over a regular location block
		include fastcgi_params;
		fastcgi_split_path_info ^/mail(/.*)()$;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME /usr/local/lib/roundcubemail/$fastcgi_script_name;
		fastcgi_pass php-fpm;
		client_max_body_size 128M;
	}

```


2. refresh

When a refresh token is used to obtain a new access token, there is a subsequent and immediate dovecot introspection attempt using the old access token. In my case, the authorization server was revoking the old access token immediately during the refresh and dovecot auth subsequently would fail. I had to rewrite part of the authorization server to delay the revocation of the old access token by a couple of seconds for refresh to work.

Example:

roundcube -> auth server
`DEBUG:__main__:FUNC issue_token: POST data=ImmutableMultiDict([('client_id', 'roundcube'), ('client_secret', 'rcm_test_123'), ('refresh_token', 'uXcC5utMAhVQ26FIQXi1tkyRieRA17lmNZzccAHt9uF1FVMi'), ('grant_type', 'refresh_token')])`

auth server -> roundcube
```
DEBUG:authlib.oauth2.rfc6749.grants.refresh_token:Issue token {'token_type': 'Bearer', 'access_token': 'rFVzKPtYTBdko6eCkrUcQ08OFYyWnsdDX4tTSBuT5k', 'expires_in': 120, 'refresh_token': 'C49MNM15o4MXuSsjKrhNjYQVGa9nARM0jyA1k1RnHNnrQguW', 'scope': 'mailbox introspect'} to <oauth.AuthClient.AuthClient object at 0x7ff9d642a3c8>
DEBUG:oauth.MyRefreshTokenGrant:revoke_old_credential: roundcube: LDwiQ0vpkIS5lbX4WJNic58oQ69VGlZEzGZc9Sgj1v
DEBUG:oauth.SqliteStorage:REVOKED: "LDwiQ0vpkIS5lbX4WJNic58oQ69VGlZEzGZc9Sgj1v" (delayed by 5s)

```
dovecot -> auth server
`DEBUG:oauth.MyAuthorizationServer:dovecot: introspect token "LDwiQ0vpkIS5lbX4WJNic58oQ69VGlZEzGZc9Sgj1v"
`
Notice that dovecot is trying to authenticate using the old access token.


3. revoke on logout?

It would be nice to support rfc7009 revocation on logout. Just a simple post to an additional endpoint...

**Comment by jones6r** [comment]
> When a refresh token is used to obtain a new access token, there is a subsequent and immediate dovecot introspection attempt using the old access token. In my case, the authorization server was revoking the old access token immediately during the refresh and dovecot auth subsequently would fail. I had to rewrite part of the authorization server to delay the revocation of the old access token by a couple of seconds for refresh to work.
> 
> Example:
> 
> roundcube -> auth server
> `DEBUG:__main__:FUNC issue_token: POST data=ImmutableMultiDict([('client_id', 'roundcube'), ('client_secret', 'rcm_test_123'), ('refresh_token', 'uXcC5utMAhVQ26FIQXi1tkyRieRA17lmNZzccAHt9uF1FVMi'), ('grant_type', 'refresh_token')])`
> 
> auth server -> roundcube
> 
> ```
> DEBUG:authlib.oauth2.rfc6749.grants.refresh_token:Issue token {'token_type': 'Bearer', 'access_token': 'rFVzKPtYTBdko6eCkrUcQ08OFYyWnsdDX4tTSBuT5k', 'expires_in': 120, 'refresh_token': 'C49MNM15o4MXuSsjKrhNjYQVGa9nARM0jyA1k1RnHNnrQguW', 'scope': 'mailbox introspect'} to <oauth.AuthClient.AuthClient object at 0x7ff9d642a3c8>
> DEBUG:oauth.MyRefreshTokenGrant:revoke_old_credential: roundcube: LDwiQ0vpkIS5lbX4WJNic58oQ69VGlZEzGZc9Sgj1v
> DEBUG:oauth.SqliteStorage:REVOKED: "LDwiQ0vpkIS5lbX4WJNic58oQ69VGlZEzGZc9Sgj1v" (delayed by 5s)
> ```
> 
> dovecot -> auth server
> `DEBUG:oauth.MyAuthorizationServer:dovecot: introspect token "LDwiQ0vpkIS5lbX4WJNic58oQ69VGlZEzGZc9Sgj1v" `
> Notice that dovecot is trying to authenticate using the old access token.
> 

@downtownallday - I'm seeing this issue also but altering the authorization server to delay the revocation of the old access token doesn' seem to be an option. I'm not knowledgeable enough to know why there is "a subsequent and immediate dovecot introspection" after a token refresh - can that be delayed?

**Comment by downtownallday** [comment]
@jones6r As far as I know, there is no way to have roundcube use the new token (or to do whatever is needed to prevent dovecot from using the old token). I ultimately switched to JWT tokens, which avoids introspection altogether as the token remains valid until it's expiry time, even if the oauth server revoked it (has a valid signature).

**Pull request merged**
