### PR TITLE
Set first thread UID as parent if no parent exists

### PR DESCRIPTION
**Pull request by HLeithner**
A regex is used to normalize the THREAD output from the IMAP Server. The regex replaces parent less threads with the first uid (mostly the oldest message) as parent. Also fixed the documentation of parse_thread.

### CODE REVIEW

**Comment by HLeithner** [comment]
Any opinion on this?

**Comment by omehegan** [comment]
I just manually tested this change against 1.3.8, and it solves the problem I wanted solved, which is that emails from GitHub do not thread in RC (even though they do in every other client I use).

**Comment by sjorge** [comment]
I just tested this against the 1.4-rc1 and this works fine for it as wel.

**Comment by HLeithner** [comment]
@alecpl it would be great if you can merge this in to 1.4.2 I'm still using and it's working perfectly.

**Comment by sjorge** [comment]
Another +1 for me, works fine and it's a bit annoying that I have to keep reapplying this after every upgrade

**Comment by alecpl** [comment]
Does not look like a complete solution. It will not "fix" threads like: `((1 2)(3))`. So, some more work is needed. It would be also nice to have some unit tests.

**Comment by alecpl** [comment]
Fixed with fded360d84.

**Comment by HLeithner** [comment]
Thanks @alecpl

**Pull request closed without merging**
