### PR TITLE
Elastic: Disable subject selection in messagelist

### PR DESCRIPTION
**Pull request by HLeithner**
In chromium based browsers it is possible to mark the text by mistake if you want to move a mail by drag'n'drop.

### CODE REVIEW

**Comment by alecpl** [comment]
I'm unable to reproduce.

**Comment by HLeithner** [comment]
hmm strange seams to be a bug in vivaldi... you can close it or merge it depends on your policy

**Comment by alecpl** [comment]
I'll consider, but maybe it should be applied to the whole `tr`, not only subject element.

**Comment by HLeithner** [comment]
That didn't worked for me, all other elements can't be marked only this span can be selected...

It seams that Javascript insert user-select: auto !important from a, this gets added when start dragging.
image

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
