### PR TITLE
remove some duplicate code in toolbar.less

### PR DESCRIPTION
**Pull request by johndoh**
I noticed there was some duplicate code with the same icons defined in .toolbar and .toolbarmenu in the toolbar mixin. I've reorganised it a little so that the icons are defined once, hopefully making it slightly easier to maintain.

### CODE REVIEW

**Review by alecpl — CHANGES_REQUESTED** [review]
I see some bugs:
1. Page navigation buttons invisible in e.g. contacts list footer.
2. Buttons in managesieve's filters list footer and list top-navigation. Note that filters list footer is to be removed/redesigned later.

**Comment by alecpl** [comment]
3. Missing icons in all .content-frame-navigation toolbars on mobile, i.e. a preview frame footer (e.g. mail preview, contact preview).

**Comment by alecpl** [comment]
I like the direction. I'd consider removing `.toolbarmenu` in favor of `.toolbar.menu` (or sth with `.popover`/`.popupmenu`) later.

**Comment by johndoh** [comment]
sorry thats really bad. not sure how i missed it. a little too much copy/paste. sorted now.

**Pull request merged**
