### PR TITLE
Try handle body part with body.peek when binary.peek cause an error on imap server (dovecot)

### PR DESCRIPTION
**Pull request by lucasmarin**
**RC Version:** 1.4.10
**Dovecot Version:** 2.3.11.3
**Capability:** [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA]

Message examples: https://skybox.skymail.net.br/s/N5NLnZoeM9boaJm (Protected by password, please send a message to me to get it) 

These messages are being successfully read in Gmail, Thunderbird and Outlook.

### CODE REVIEW

**Comment by alecpl** [comment]
I don't like it. What version of dovecot are you using?

**Comment by lucasmarin** [comment]
Hi @alecpl. I updated the PR with more info.

If you want to downlod the message examples, please send me an e-mail on lucasmarin@gmail.com.

Thx

**Comment by alecpl** [comment]
I would rather ask dovecot developers to do something with it, because it's an evident dovecot bug.

**Comment by lucasmarin** [comment]
I think we can ask dovecot to do something about it too... and also deal with dovecot erros retrying read these e-mails with another way (body.peek). 

Maybe this is not the better way to do it, but the fact another clients read these e-mail doesn't make you think about why RC don't?

**Comment by alecpl** [comment]
The clients you mentioned just don't use binary fetches, they fetch the whole message and parse it by themselves. That's the difference. For performance reasons Roundcube uses other standard ways and depends on them being not buggy.

**Comment by alecpl** [comment]
Reconnecting on error is that kind of a server bug workaround I don't like in general.

**Comment by alecpl** [comment]
BTW, you can disable use of BINARY either via Roundcube config (`imap_disabled_caps`) or via Dovecot config.

**Pull request closed without merging**
