### PR TITLE
Apple Mail send image files marked as inline even if it is not on body message (#7414)

### PR DESCRIPTION
**Pull request by lucasmarin**
Fix to reported issue https://github.com/roundcube/roundcubemail/issues/7414

Attached two e-mails with reported problem:

[mail.txt](https://github.com/roundcube/roundcubemail/files/4795204/mail.txt)
[Comprovante de Up Grade.txt](https://github.com/roundcube/roundcubemail/files/4795209/Comprovante.de.Up.Grade.txt)

### CODE REVIEW

**Comment by alecpl** [comment]
Thanks, we might apply that change as a quick workaround, but I think we need a more general solution for handling images that are marked as inline, but are not used in the html body.

**Comment by lucasmarin** [comment]
I agreed. I don't know if this will be default behavior of apple client and there are another mail clients with that behavior too.

**Comment by alecpl** [comment]
I just noticed that these messages do not have a HTML part, so checking if HTML part exists might be a better fix.

**Comment by alecpl** [comment]
Fixed via ec2e713.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9150
- https://github.com/roundcube/roundcubemail/issues/5051
- https://github.com/roundcube/roundcubemail/issues/6279
- https://github.com/roundcube/roundcubemail/issues/7117
- https://github.com/roundcube/roundcubemail/issues/7122
- https://github.com/roundcube/roundcubemail/issues/7214
- https://github.com/roundcube/roundcubemail/issues/7293
- https://github.com/roundcube/roundcubemail/issues/7414
- https://github.com/roundcube/roundcubemail/issues/7440
- https://github.com/roundcube/roundcubemail/pull/7441

**Pull request closed without merging**
