### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by miaulalala**
Add Nextcloud HackerOne link instead of mail addresses

### CODE REVIEW

**Comment by xkill** [comment]
Report on nextcloud? Why?

**Comment by alecpl** [comment]
It supposed to be added as an extra channel, not replacing the old one. I still want to be a target for security reports. We can remove Thomas's email, and/or add another one i needed.

**Comment by xkill** [comment]
But Nextcloud is not Roundcube. I don't know why the security report related to Roundcube have to be reported on Hackersone Nexcloud. Moreover, nextcloud has it's own mail app (it also supports to integrate Roundcube, but is a 3rd party app, not the official one).

**Comment by alecpl** [comment]
https://roundcube.net/news/2023/11/30/nextcloud-the-new-home-for-roundcube

**Comment by xkill** [comment]
> https://roundcube.net/news/2023/11/30/nextcloud-the-new-home-for-roundcube

Thanks for the clarification!!!

**Comment by miaulalala** [comment]
@alecpl can we merge? Since we discussed this :)

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
