### PR TITLE
Allow multiple messages to be bounced/resent at once

### PR DESCRIPTION
**Pull request by endnil**
This PR extends the bounce interface to allow multiple messages to be selected and bounced to the same recipient.

It also sneaks in a change to remember (in a user pref) the folder the bounced messages were last saved in.  (I'm happy to separate this out if needed, though.)

Please let me know if any other changes are needed.  Thanks for all your work on Roundcube.

### CODE REVIEW

**Comment by alecpl** [comment]
I don't like the idea because it has performance implications, and it probably does not work when you select all messages (using "select all").

**Comment by endnil** [comment]
No worries, thank you for the feedback @alecpl.

Indeed, I see now that it doesn't work with the select all function.

Are the performance implications to do with the increase in response time when sending and saving multiple messages?

I'm happy to spend some more time on this if it will be useful.

**Comment by alecpl** [comment]
> Are the performance implications to do with the increase in response time when sending and saving multiple messages?
This too but imagine a user bouncing a whole folder with thousends of messages, or even less messages but with big size.

Because of that zipdownload plugin has a limit, but doing the same for bounce might not be as reliable.

**Comment by endnil** [comment]
Thanks for explaining. I can see how while this works well for our niche use-case, it's not generally suitable.

**Pull request closed without merging**
