### PR TITLE
Foundation for customizable contacts autocomplete

### PR DESCRIPTION
**Pull request by bostjan**
These ~~five~~ seven commits lay the foundation for development of plugins that will provide more intelligent contacts autocomplete suggestions without patching RC itself.

Some of this was already discussed in the issue #5196.

Please review and comment, suggestions welcome.

PS: Also, can this be merged back to 1.1 branch too?

### CODE REVIEW

**Comment by bostjan** [comment]
Please freeze this pull request - upcoming additional changes in a couple of hours.

It turns out I did not anticipate everything correctly before plugin development actually started :)

**Comment by bostjan** [comment]
I have updated my branch with two more commits, and now it is ready for review and potential merge.

Summary of changes:
- provide data to autocomplete hooks from RC autosuggestions (add IDs, types, sources)
- provide data to autocomplete_insert event, main additions being original search string and all data about contact suggestion that was selected.

Please review and comment on merge-ability in 1.2.0 and 1.1.5.

b.

**Comment by alecpl** [comment]
Could you elaborate more about use-cases for your client-side changes?

**Comment by bostjan** [comment]
I tried my best yesterday to publish a plugin on plugins.roundcube.net, but:
https://github.com/roundcube/plugins.roundcube.net/issues/4

Initial code for smart autocomplete plugin is here:
https://github.com/teonsystems/roundcube-plugin-smart-autocomplete

The summarized reason is this:
If you want you autocomplete to adjust to user's habits, you need not only suggest as best as you can, but you have to track which autocomplete suggestions user actually selects AND input string they correlate to, and make next autocomplete suggestions better based on stats gathered.

To do **precise** tracking, you need to be able to make a callback whenever user selects AC suggestion, in the manner of register_accepted_suggestion($searchString, $contactId, $contactType, $contactSource).

Am I clear enough?

Or let me put it in UX perspective:
Autocomplete with alphabetic ordering is better than no autocomplete at all, but it is still slow. If 99% of times I send email to Bostjan Skufca when I type in "bostjan s", I would really appreciate if eventually correct contact comes up as first suggestion when I enter only the first letter "b").


From maintainer's perspective:
Either I do a better implementation of plugin X myself, or I design my product's architecture in such a way that enables contributors to do what they need/want and I will probably receive some wacky suggestions/contributions, but also some very powerful ones which I have not thought of, despite my best effort.

The actual usecase:
I am migrating from Gmail with 2k contacts imported, and current autocomplete implementation is super annoying and/or a showstopper. I would really like to see RC's AC behaviour that Gmail has, and mentioned upcoming plugin provides it.

**Comment by alecpl** [comment]
Ok, I thought you will do "tracking" when the email is send, but indeed this would give you only prioritization of recipients, but would not map a search key with them.

**Comment by bostjan** [comment]
Bingo :)

Yes, doing tracking when email is sent is possible, but the information about which contact was used is lost there - you only get email address and name from T/C/B: headers. While working back doing search through addressbooks to get reference to contact used is certainly possible, well... :)

Off topic:
Actually, let me delve a little deeper while secretly eyeing towards "When you send email to these two recipients, you usually send email to this one too" capability.

It would not be bad if RC frontend tracked To:/Cc:/Bcc: entries internally as references to contact objects when applicable (if autocomplete suggestion was used). I have not thought a lot about this as it is not on my priority list, but I think this is what Gmail did when they implemented this functionality. (with Gmail, you can notice that addresses, once entered, can not be edited again, just deleted and reentered).

PS: I hate to mention Gmail that much, but they did get certain things right.

**Pull request merged**
