### PR TITLE
Managesieve plugin: sieverules compatibility

### PR DESCRIPTION
**Pull request by marczi**
This PR adds on-the-fly conversion for sieve scripts that contain disable rules created by the abandoned sieverules plugin.
That plugin uses PHP serialization to add the disabled rule as a comment to the script. This modification can convert that PHP object structure to the format that the Managesieve plugin understands

### CODE REVIEW

**Comment by alecpl** [comment]
Something's went wrong. I suppose a rebase is needed or something.

**Comment by marczi** [comment]
Dear @alecpl I've fixed this PR as well, please rewrite it. Thanks in advance

**Comment by alecpl** [comment]
It would be nice to have a test for this feature.

**Comment by marczi** [comment]
Dear @alecpl thanks for the suggestion, I've added a test script. It helped to fix a warning of checking an undefined array key

**Comment by alecpl** [comment]
The feature has been removed for security reasons. We don't want `unserialize()` on a user provided input.

**Pull request merged**
