### PR TITLE
Added an Option to Hide Organization from the New User Dialog

### PR DESCRIPTION
**Pull request by rmcaninch**
First try at this. I'm not sure if I got all the pieces right, but it is working for me.

### CODE REVIEW

**Comment by alecpl** [comment]
You still have the organization field in identity form in settings. So, what's the point? Or you use identity_form hook to hide it there? Then, maybe would be better to provide a plugin hook in new_user_dialog?

**Comment by rmcaninch** [comment]
I just wanted to hide the field in the new user dialog so as not to distract my users. Having it remain in the settings page is fine. Is there a better way to approach this then?

**Comment by alecpl** [comment]
This just does not sound right to me. Organization is distracting but signature is not?

**Comment by rmcaninch** [comment]
Well in my case I'm deploying Roundcube for a company where everyone would have the same Organization and having it in the new user dialog doesn't seem to do any good for me so I wanted to hide it. The simpler the better :) And thought someone else might find it useful to turn off a field in the dialog. Could add an option to turn off the signature too. Not a big deal.

**Comment by alecpl** [comment]
Well, for such cases I'd prefer a new core config option (e.g. identities_organization='Organization name') which would hide organization field in identity form and new_user_dialog and store configured value in the identity. Would you like to provide a PR for this?

**Comment by rmcaninch** [comment]
I will try to look at that.

**Pull request closed without merging**
