### PR TITLE
Fix CS - imports

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by mvorisek** [comment]
Is the E2E CI failure related?

**Comment by alecpl** [comment]
"Cannot declare class Tests\Browser\Browser because the name is already in use." in tests/Browser/Browser.php

**Comment by mvorisek** [comment]
Thank you, I will fix the CS Fixer soon.

**Comment by mvorisek** [comment]
Thank you. I did the first 2 commits in the past using older PHP CS Fixer verison... Now the PR is passing and I checked the changes againts latest fixer applied on master.

**Pull request merged**
