### PR TITLE
Update idn convert

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by alecpl** [comment]
Does it fix anything? If not, I don't like the callback idea.

**Comment by danielkesselberg** [comment]
I dropped the callback. It does not fix anything at all.

**Comment by alecpl** [comment]
I didn't check, but will that work for addresses as 'рф.ru@рф.ru', 'xn--p1ai.ru@xn--p1ai.ru'?

**Comment by danielkesselberg** [comment]
Good catch. I added this as test case and restored the old version.

**Pull request merged**
