### PR TITLE
Keep phpstan strict rules testing

### PR DESCRIPTION
**Pull request by mvorisek**
Keep phpstan strict rules for CI.

Too strict rules with many matches should be ignored by regex instead, but overall the quiality should be asserted, the rules are great!

### CODE REVIEW

**Comment by mvorisek** [comment]
@alecpl can this PR be merged?

**Comment by alecpl** [comment]
I appreciate your commitment, but I'm against this change.

**Comment by mvorisek** [comment]
Given all the detected issues are valid, I kindly ask if this PR can be merged in order to maintain the project in unarguably a better shape.

In my opinion, the few needed `@phpstan-ignore` comments (of real issues to be fixed someday) are worth and the few ignores of too strict errors in phpstan config does not hurt either.

**Comment by pabzm** [comment]
@alecpl Can you explain why you're against this?
I don't know if I agree with every rule, but in general I would prefer to have advanced automated syntax/style checking, as it helps contributors to conform to the wanted rules and thus requires a little less attention from you (or the team).

**Comment by mvorisek** [comment]
@alecpl Can you explain why you're against this?

In https://github.com/roundcube/roundcubemail/pull/9424#issuecomment-2144897599 I have summarized the reasons why the changes in this PR are good and help to maintain this project in better shape. It is fine to ignore some too strict rules, but not all of them, some are legit.

**Comment by mvorisek** [comment]
@alecpl I have rebased this PR, let's merge it.

**Comment by alecpl** [comment]
Ok, let's do it. After the conflict is resolved.

**Comment by mvorisek** [comment]
@alecpl conflicts are resolved

**Pull request merged**
