### PR TITLE
ALL-INKL.COM driver for password plugin

### PR DESCRIPTION
**Pull request by Dennis1993**
I've programmed a driver for ALL-INKL.COM to change the users mail password. It works with the KAS API and SOAP.

### CODE REVIEW

**Comment by Dennis1993** [comment]
...

**Comment by jankal** [comment]
Why has this never been merged? @Dennis1993 
Besides the `raise_error` function which should now be `rcube::raise_error`, everything is still working here.

**Comment by Dennis1993** [comment]
I don’t know... :(

**Comment by jankal** [comment]
@alecpl Could you please consider looking into this?

**Pull request closed without merging**
