### PR TITLE
[WIP] Rewrite Dockerfile

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@alecpl would you like to give me any feedback, if it's worth to spent more time on this?

**Comment by alecpl** [comment]
Personally I'm not interested in supporting Docker. I don't know Docker. Maybe @thomascube, @prashantjois @doublerr, @swarren83, @alunduil

**Comment by thomascube** [comment]
I don't understand why the new Dockerfile downloads the package from Github. I suggest a Docker build using the integrated Dockerfile should use the sources and then basically perform the actions described in [Build From Source](/roundcube/roundcubemail/wiki/Build-from-source).

**Comment by J0WI** [comment]
This is to avoid installing unnecessary packages, like Composer or Git. The result should be the same.
Compression of CSS/JS can be done by a reverse proxy.

**Comment by thomascube** [comment]
Implemented in master therefore closing this PR. Thanks a lot for the inspiration!

**Pull request closed without merging**
