### PR TITLE
bring %s variable support in setting smtp_server

### PR DESCRIPTION
**Pull request by arnisoph**
%s is available in defaut_host so providing %s variable support in smtp_server should be also possible since when you're using imap.domain.de you often have smtp.domain.de, too.

### CODE REVIEW

**Comment by thomascube** [comment]
@alecpl what's your take on this?

**Comment by alecpl** [comment]
Not bad, but there's small problem. %s might be resolved to different values on login and on smtp connect. This might be confusing. Anyway, %t, %d, %z is really not enough?

**Comment by bechtoldt** [comment]
@alecpl 

Well there are people on this planet whose smtp server 

* isn't running on the same host/ ip address as the webmail server
* isn't running on the same host as the imap server

Since it's possible to have %s in ``$config['default_host']`` why not providing it in ``$config['smtp_server']``, too?

**Comment by alecpl** [comment]
I still think this can be done with other variables, but if we really need this I'd go with different variable name, maybe using a capital S.

**Comment by bechtoldt** [comment]
@alecpl Which variable could be used for the case explained above?

**Comment by alecpl** [comment]
If your imap server is imap.domain.de and you want smtp_server to be smtp.domain.de set smtp_server to "smtp.%z".

**Comment by bechtoldt** [comment]
@alecpl That seems to work. Looks like I misunderstood %z. 

Sorry for the confusion!

Closing PR since there isn't an use case left for this.

**Pull request closed without merging**
