### PR TITLE
added source to image file to deploy on openshift

### PR DESCRIPTION
**Pull request by ombre8**
This file allows Openshift to deploy and install Roundcube automaticly on Openshift.

### CODE REVIEW

**Comment by alecpl** [comment]
Thanks, but we'll rather not merge it.

**Comment by ombre8** [comment]
Hi @alecpl 
is there a reason why?
Greetings

**Comment by alecpl** [comment]
If we add something we have to support it. That's why we also remove docker files from the repo.

**Comment by ombre8** [comment]
Ok I get that, so for Documentation purpose, if someone else would like to deploy roundcube on Openshift here is what you can do:

Configure the build config as followed:
```
[...]
    source:
    git:
      ref: release-1.4
      uri: https://github.com/roundcube/roundcubemail.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.1
        namespace: openshift
      scripts: https://raw.githubusercontent.com/roundcube/roundcubemail/d7b60c4d08ebfc4c7bf97b6126d09fd472df92bf/.s2i/bin/
    type: Source
[...]
```

**Pull request closed without merging**
