### PR TITLE
Fix two language typos for danish

### PR DESCRIPTION
**Pull request by peter-toft-greve**

### CODE REVIEW

**Comment by peter-toft-greve** [comment]
This is golden - I find two typos, I can checkout the code, clone, make a patch in 3 minutes.... Nice.

**Comment by alecpl** [comment]
However, this has to be done via https://www.transifex.com/roundcube/roundcube-webmail/, otherwise the changes will be overwritten next time we update localizations.

**Comment by peter-toft-greve** [comment]
@alecpl Thank you - is there someone who can cherrypick this fix to the right repo?
I will not make a 70 USD/year account for this cf. https://www.transifex.com/pricing/

**Comment by alecpl** [comment]
I updated the label on Transifex for you. BTW, the translator-role account is free.

**Comment by peter-toft-greve** [comment]
@alecpl ok - I have added a petertoft account over at Transifex. I can take some Danish stuff

**Comment by peter-toft-greve** [comment]
@alecpl I can help with english -> danish translations. Now I have the Transifex account - no clue on how I get started :)

**Comment by alecpl** [comment]
You have to request to join the Danish localization team, somewhere in the Transifex UI. Should be somewhere on this page https://www.transifex.com/roundcube/roundcube-webmail/language/da_DK/

**Comment by peter-toft-greve** [comment]
I have requested it @alecpl

**Comment by peter-toft-greve** [comment]
@alecpl true that the "sigseparator" is now gone - cannot find any translation for this.
I have translated and changed a few others :)

**Pull request closed without merging**
