### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by gerbert**
Added JetBrains PhpStorm project folder (.idea)

### CODE REVIEW

**Comment by gerbert** [comment]
One minor note I noticed in .gitignore, lines 25-27. Shouldn't the pass be relative?

```
# eslint dependencies                                                            
/node_modules
/package.json
/package-lock.json
```

**Comment by pabzm** [comment]
> Shouldn't the path be relative?

The paths are all relative to the repo's root directory, see <https://git-scm.com/docs/gitignore#_pattern_format>:
> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

**Comment by pabzm** [comment]
@alecpl I allowed myself to merge without further review because the change is so tiny and simpel.

**Comment by gerbert** [comment]
> > Shouldn't the path be relative?
> 
> The paths are all relative to the repo's root directory, see https://git-scm.com/docs/gitignore#_pattern_format:
> 
> > If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

Well, thanks for pointing out, never knew, actually. Might be handy in the future.

**Pull request merged**
