### PR TITLE
IMAP Servers may timeout for a login request.

### PR DESCRIPTION
**Pull request by hefee**
When connection fails in a recoverable way, we should retry to connect
to the server again. The code in rcube_imap.php looks, like, that is
already prepared for a retry, but `data['retry']` is not used anywhere.

### CODE REVIEW

**Comment by alecpl** [comment]
That 'retry' item was there to give plugins opportunity to e.g. retry using another imap server or sth else. I don't think we should retry by default.

**Comment by hefee** [comment]
> That 'retry' item was there to give plugins opportunity to e.g. retry using another imap server or sth else. I don't think we should retry by default.

@alecpl: I see your point, that this is code, that my solution fixes a specific issue on a very generic point and move this to a plugin makes more sense. But how do I write such a plugin? I'm happy to implement. But I see that it does not affect a lot of setups, otherwise this issue would attract more attention. I searched in previous issues and found, that also others have/had this issue, too. about imap sever, that just does not answering #5393.

**Comment by alecpl** [comment]
Sample plugin code that uses `storage_connect` hook: https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_sso/kolab_sso.php$169 (put that in `init()` method) and https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_sso/kolab_sso.php$201

**Comment by ibizara** [comment]
There's a patch issued in the Roundcube debian package found at https://packages.debian.org/buster-backports/roundcube named retry_to_reach_imap_server.patch, however this causes the issue https://github.com/roundcube/roundcubemail/issues/7754

**Pull request closed without merging**
