### PR TITLE
Added exec_hook to send error to an external error tracking tool

### PR DESCRIPTION
**Pull request by AllanKlaus**
I'm working with roundcube and I felt the need of a hook to send a log to my error tracking tool when rouncube handles an exception. So I add a hook to do it in using a plugin.

issue  #6199

### CODE REVIEW

**Comment by alecpl** [comment]
The hook should be named just `raise_error`. I guess we could also extend that a little bit so plugins can modify $args or abort the execution.

**Comment by AllanKlaus** [comment]
@alecpl nice suggestions, I changed it.

**Comment by AllanKlaus** [comment]
Can I do something else?

**Comment by alecpl** [comment]
I think it would make sense to move that code later in this function, i.e. after the $arg input has been unified. So, plugin author does not have to do all that conversion that is in the start of the raise_error() method. Also, I guess we could add `$arg['cli'] = $cli; $arg['log'] = $log; $arg['terminate'] = $terminate;` before.Please, use 4-spaces indent.

**Comment by AllanKlaus** [comment]
@alecpl nice.

I have done:
- Moved hook to later in function
- Added `$arg['cli']; $arg['log']; $arg['terminate'];`
- Removed `$arg['abort']` because, later in function `$arg` is overwrited.

**Pull request merged**
