### PR TITLE
elastic: message headers view changes

### PR DESCRIPTION
**Pull request by johndoh**
reference #7224

based on comments in the referenced issue this pr moves the "details" link up to the envelope summary line and changes the icon for expand/collapse. it also makes the status of the envelope block remembered between page loads.

Untitled-1

### CODE REVIEW

**Comment by rdacn** [comment]
This update will be surely well regarded by our users, however there is still another complaint : they would like to see the username and the email address in the From field, instead of just the username

**Comment by alecpl** [comment]
The envelope icon without a visible label is not that clear.

I'd try with leaving Details link where/how it was, but change the behavior so it hides the `.header-subject` element when `.headers-table` is visible and vice-versa.

**Comment by johndoh** [comment]
hows this?

Untitled-1

**Comment by alecpl** [comment]
Now, when the "extended" header can be used in "always on" mode, it would make sense think about improving it, e.g. get rid of the border. Also, maybe it would be better to put "All headers" ("Headers") in the same line as "Summary". I'm not sure what icon we could use. How about  `envelope` for "Headers" and `info` for Summary/Details?

**Comment by johndoh** [comment]
Hows this?
Untitled-1

**Comment by alecpl** [comment]
Much better. I'm not sure yet I like the icons.

**Comment by alecpl** [comment]
I think that Headers link could be always visible now, i.e. also in short header mode.

**Comment by johndoh** [comment]
Making the Headere link always visible is a simple CSS change but I'll leave this for now and take some more time to think about the icons.

**Comment by johndoh** [comment]
What about keeping the envelope icon for details as it is currently and using the info icon for headers?
Untitled-1

**Comment by alecpl** [comment]
It could work if we don't find a better option. I guess, if we replace Headers and Details icons it would work as well.

**Comment by johndoh** [comment]
The info icon is only available in solid type, that's why I kept them that way around.

**Comment by alecpl** [comment]
Looking at the code only... You removed some styling from `.message-partheaders` which is also used to display headers on message/rfc822 parts. I think this needs some fixes. We should probably not use that class inside `.header-envelope`. We probably don't need the `.headers-table` parent at all.

**Comment by johndoh** [comment]
The display of message/rfc822 parts looks fine to me. it uses the same message template as the regular display so it has the same changes as that. unless I am misunderstanding.

About the current DOM structure with `.short-header`/`.header-envelope`/`.message-partheaders`/`.headers-table`. I was trying to keep my changes as minimal as possible but if you are happy with something a bit more radical then I could work on it.

You like the Details/Summary, Headers, Plain text/HTML buttons in a row at the bottom right (pending decision on the icons)? So this would be more about cleaning up the DOM than any more visual changes.

**Pull request merged**
