### PR TITLE
Fix error in german translation.

### PR DESCRIPTION
**Pull request by heptalium**

### CODE REVIEW

**Comment by alecpl** [comment]
Please, use Transifex service. Otherwise this can be overwritted by localization update in the future. We usually update localizations from Transifex service before every release.

**Comment by heptalium** [comment]
How does this work? If I call the URL from the file I just get a 403 error message.

**Comment by alecpl** [comment]
Try this https://www.transifex.com/roundcube/roundcube-webmail/translate/#de_DE/plugin-enigma

**Comment by CRtEurope** [comment]
I get a 404 error
unbenannt

**Comment by heptalium** [comment]
I'm too (after creating an account)

**Comment by alecpl** [comment]
Maybe you need to login first. Hopefully this works: https://www.transifex.com/roundcube/roundcube-webmail/plugin-enigma

**Comment by heptalium** [comment]
I can call the URI, but then I can't do anything.

**Comment by CRtEurope** [comment]
Me'nt either

**Pull request closed without merging**
